language: minimal

dist: bionic

addons:
    apt:
        packages:
            - libssl1.0.0
            - python3
            - python3-pip
            - python3-setuptools

before_script:
  # Download and unzip the zola executable
  # Replace the version numbers in the URL by the version you want to use
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

script:
  - zola build

# If you are using a different folder than `public` for the output directory, you will
# need to change the `zola` command and the `ghp-import` path
after_success: |
  [ $TRAVIS_BRANCH = dummy ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  zola build &&
  cp keybase.txt public/ &&
  pip3 install wheel &&
  pip3 install ghp-import &&
  ghp-import -c jeremy.savor.page -n public -b master &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
